source 'https://rubygems.org'

gem 'rails', '4.2.2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'therubyracer'

gem 'mysql2'
gem 'activerecord-mysql-awesome'
gem 'ridgepole'

gem 'slim-rails'
gem 'quiet_assets'
gem 'asset_finder'
gem 'weak_parameters'
gem 'deep_merge'
gem 'rails_config'
gem 'dotenv-rails'

source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap'
  gem 'rails-assets-jquery-ujs'
end

group :development do
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'rspec', '~> 3.3'
  gem 'rspec-rails'
  gem 'rspec-power_assert'
  gem 'database_rewinder'
  gem 'guard-rspec'
  gem 'spring-commands-rspec'
  gem 'terminal-notifier-guard'
  gem 'terminal-notifier-guard'
  gem 'factory_girl_rails'
  gem 'ffaker'
  gem 'autodoc'
end

group :production do
  gem 'unicorn'
  gem 'unicorn-worker-killer'
end

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
